### ISSUE TITLE
SyncSession does not call error handler

### ISSUE THREAD

**Issue by blagoev** [realm/realm-object-store#589] opened 2017-10-31 09:31 UTC
This surely is a bug. The `handle_error` method does not take into consideration that there might be an error handler and silently skips errors
https://github.com/realm/realm-object-store/blob/master/src/sync/sync_session.cpp#L629

This happens when investigating ssl connection for this bug https://github.com/realm/realm-js/issues/1369
The server returns 
```
Sync Error
336134278 error_code
message "certificate verify failed"
```

which is not recognized and the sync error handler is not called
This is ROS 1 and realm-js 1.13 still I think it should be fixed for 2.0 as well

**Comment by nirinchev** [comment] 2017-10-31 09:35
Wouldn't that happen only if the error is unknown? I guess the bug is that the server returns an unknown error_code, not in the OS error handling logic.

**Comment by blagoev** [comment] 2017-10-31 09:38
I think both. The server should be using known errors but still the client should be redirecting this to user error handler. At least for debugging such cases it would help. Or the client can take appropriate actions to recover/show error message etc even when the error is not know

**Comment by nirinchev** [comment] 2017-10-31 10:05
I'm not sure the application can take appropriate steps if we have no idea what the error code means - it could just as well be a bit flip due to gamma radiation :) At the very least, the server should set the appropriate category. @morten-krogh do you have any idea why the server would return an unrecognized error_code?

**Comment by blagoev** [comment] 2017-10-31 10:57
Yes exactly we can't be sure so we give the developer to opportunity to decide  by the error callback means. Not respecting the error handler means we are deciding for him. In this particular case I think we must call the error handler with the information we have ie unknown error code and the exact message. 
If i am the developer in this case it will provide the means to tell the user something went wrong. Silencing this error means my app will still be showing a progress bar/spinner for example.

The server should return known errors but we have a precedent that it sometimes does not. So we should be respecting the error handler in the sync client code regardless. 

IMO silencing the error should happen only when no error handler is set. Otherwise the error should be redirected to the developer to worry him at least :)

**Comment by morten-krogh** [comment] 2017-10-31 12:21
I agree that the errors should not be discarrded by object store. 
I have actually seen the behavior before.

We have had various discussions about the sync error codes. 

The system is that low level error codes go through the whole chain and can be captured by 
any layer above.

This error

Sync Error
336134278 error_code
message "certificate verify failed"

originates from OpenSSL. There is something strange with some of the OpenSSL error codes.
Anyway, the message is quite informative.

If sync uses the principle of sending low level error codes through, it is intended that all bindings capture them and submit them as is to the user or transform them before giving them to the user.

I agree with you that the bindings should deliver it to the user. That is all there is to do.
The user will have to look a the SSL certificates. There is no point in continuing.

This means that Object store should pass the error code along, and the binding should report it to the user.  The current situation is not the intended behavior.

**Comment by austinzheng** [comment] 2017-11-08 00:37
This is a straightforward change, and probably should have been made long ago.

**Comment by austinzheng** [comment] 2017-11-14 19:15
Fixed by https://github.com/realm/realm-object-store/pull/596.

**Closed by austinzheng** 2017-11-14 19:15 UTC
Labels: O:User PE/EE, T:Bug
