### ISSUE TITLE
Add delete_realm function

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-object-store#218] opened 2016-11-14 12:22 UTC
The bindings have their own (or no) implementation of `deleteRealm` etc. -- the knowledge about which files should be deleted belongs in object store, so we should implement a function here that the bindings can use.

**Comment by jpsim** [comment] 2016-11-14 17:34
FWIW there's already some code to delete a Realm in the object store: https://github.com/realm/realm-object-store/blob/c44f81c70e52d78cd9714222f94de56e684dad76/src/shared_realm.cpp#L291, but it could be expanded to also delete auxiliary files (e.g. `.management/*`, etc) and extracted to its own function.

**Comment by austinzheng** [comment] 2016-11-16 21:10
There are a couple of Realm and general file management APIs in `sync_file.hpp`, but most of them were written with sync in mind. Perhaps there might be something worth using from there.

**Comment by AndyDentFree** [comment] 2016-11-18 16:28
Should `delete_realm` be an _out-of-band_ command which can be propagated via sync?

Once deleted, you don't need to sync any incomplete previous operations.

**Comment by nirinchev** [comment] 2021-02-22 13:36
Duplicate of https://github.com/realm/realm-core/issues/4424.

**Closed by nirinchev** 2021-02-22 13:36 UTC
Labels: T-Enhancement
