### ISSUE TITLE
Problem on compilation

### ISSUE THREAD

**Issue by ovr** [realm/realm-object-store#418] opened 2017-03-27 10:14 UTC
Hey! I am using realm-js `v1.1.1`

Error

```
/Users/ovr/projects/interpals/frontend/native/node_modules/realm/src/object-store/src/object.cpp:42:20: error: no viable overloaded '='
        m_notifier = std::make_shared<_impl::ObjectNotifier>(m_row, m_realm);
        ~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/ovr/projects/interpals/frontend/native/node_modules/realm/src/object-store/src/object.cpp:19:
In file included from /Users/ovr/projects/interpals/frontend/native/node_modules/realm/src/object-store/src/object.hpp:22:
/Users/ovr/projects/interpals/frontend/native/node_modules/realm/src/object-store/src/impl/collection_notifier.hpp:256:13: note: candidate function not viable: no known conversion from 'typename enable_if<!is_array<ObjectNotifier>::value, shared_ptr<ObjectNotifier> >::type' (aka 'std::__1::shared_ptr<realm::_impl::ObjectNotifier>') to 'const realm::_impl::CollectionNotifier::Handle<realm::_impl::ObjectNotifier>' for 1st argument
    Handle& operator=(const Handle& other)
            ^
/Users/ovr/projects/interpals/frontend/native/node_modules/realm/src/object-store/src/impl/collection_notifier.hpp:265:13: note: candidate function not viable: no known conversion from 'typename enable_if<!is_array<ObjectNotifier>::value, shared_ptr<ObjectNotifier> >::type' (aka 'std::__1::shared_ptr<realm::_impl::ObjectNotifier>') to 'realm::_impl::CollectionNotifier::Handle<realm::_impl::ObjectNotifier>' for 1st argument
    Handle& operator=(Handle&& other)
            ^
1 error generated.
```

My ENV

```
clang -v
clang version 4.0.0 (tags/RELEASE_400/final)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
```

Thanks

**Comment by austinzheng** [comment] 2017-03-27 16:20
Thanks for filing an issue! This repository is for the object store, which is an internal component of Realm. I've cross-filed your bug to the [realm-js repository](https://github.com/realm/realm-js) and will be closing this ticket.

**Closed by austinzheng** 2017-03-27 16:20 UTC

**Comment by ovr** [comment] 2017-03-28 04:20
Hey! Thanks for move this issue, but `src/object-store/src/object.cpp:42:20` looks like it's object-store problem and posted here :)

**Comment by austinzheng** [comment] 2017-03-28 14:59
This repo isn't intended for public issue tracking. Our bindings engineers triage bugs and then reassign them as necessary. Some bugs that appear to originate in object store code may be caused by a bug in the binding code.
