### ISSUE TITLE
Session lookup after changing server address

### ISSUE THREAD

**Issue by kvap** [realm/realm-object-store#618] opened 2017-12-22 14:28 UTC
The object store consistently fails to look the session up, if you initially open a sync URL like `http://127.0.0.1/asd` and later open it as `http://localhost/asd` (using the same local realm). The logs (`realm-js` client) say:

```
Unhandled session token refresh error: could not look up session at path /Users/kvap/temp/node/asd.realm
TypeError: Cannot read property 'config' of undefined
    at performFetch.then.then (/Users/kvap/temp/node/node_modules/realm/lib/user-methods.js:103:42)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

Removing `sync_metadata.realm` helps. Removing just the old session from it also helps. So my guess is that a session associated with the old URL obscures the session with the new URL.

**Comment by bdash** [comment] 2017-12-22 15:14
What do you mean by "fails to look the session up"? Can you share what object store code is involved?

**Comment by kvap** [comment] 2017-12-22 15:19
`_sessionForOnDiskPath()` in realm-js returns `undefined`, this means that `SyncUser::session_for_on_disk_path()` returns `nullptr`.

**Comment by bdash** [comment] 2017-12-22 15:22
I don't see any information in this report, nor the linked object server issue, about how to reproduce this problem. Can you please share the steps to reproduce, assuming you're able to do reproduce?

**Comment by bdash** [comment] 2017-12-22 15:24
> The object store consistently fails to look the session up, if you initially open a sync URL like http://127.0.0.1/asd and later open it as http://localhost/asd (using the same local realm).

Is this referring to using `SyncSession::override_server` to change which server the session is using? If not, what?

**Comment by kvap** [comment] 2017-12-22 15:25
No, this is not about `override_server`. I will provide an example.

**Comment by kvap** [comment] 2017-12-22 15:51
Ok, so the example is this code:
```js
const Realm = require('realm');

const schema1 = {
	name: 'One',
	properties: {
		id: 'int',
		value: 'string',
	},
};

function doStuff(ros, localpath) {
	return Realm.Sync.User.login(`http://${ros}`, 'realm-admin', '')
		.then((user) => {
			return Realm.open({
				sync: {
					url: `realm://${ros}/asd`,
					user: user,
				},
				path: localpath,
				schema: [schema1],
			});
		})
		.then(() => {
			process.exit(0);
		});
}

doStuff(process.argv[2], process.argv[3]);
```

If you run it like this:
```sh
node example.js 127.0.0.1:9080 asd.realm
node example.js localhost:9080 bsd.realm
```
it will fail to establish the session on second run, even though it is a different local path.

**Comment by bdash** [comment] 2017-12-22 15:53
Thanks, I'll take a look.

**Comment by bdash** [comment] 2017-12-22 15:54
Just to confirm: is the use of two different file names (asd.realm then bsd.realm) intentional in your instructions?

**Comment by kvap** [comment] 2017-12-22 15:55
It will also fail with the same local path. Just wanted to show that the error is not caused by using the same local path.

**Comment by bdash** [comment] 2017-12-22 15:55
Thanks for clarifying.

**Comment by bdash** [comment] 2017-12-22 16:13
The issue appears to be that JS is somehow retrieving the wrong user. The same user ID exists for two different server addresses, only one of which is associated with the open session. I'm not yet clear how JS ends up working with the wrong user.

**Comment by bdash** [comment] 2017-12-22 16:17
Oh, it's because of [this](https://github.com/realm/realm-js/blob/1b0f6c0b21149fea322471c615822abb751e06ca/lib/user-methods.js#L91-L94):
```js
// Look up a fresh instance of the user.
// We do this because in React Native Remote Debugging
// `Realm.clearTestState()` will have invalidated the user object
let newUser = user.constructor.all[user.identity];
```

The JS binding is assuming that users are uniquely identified by their identity, when they're in fact identified by the combination of (identity, server).

**Comment by bdash** [comment] 2017-12-22 16:23
I'm going to close this since it's an issue in realm-js rather than object store.

**Closed by bdash** 2017-12-22 16:23 UTC
