### ISSUE TITLE
Direct access in function [...] to global weak symbol linker warning

### ISSUE THREAD

**Issue by jpsim** [realm/realm-object-store#281] opened 2016-12-05 23:56 UTC
Seeing this warning with bedfafd

```
(null): Direct access in function 'realm::util::InterprocessMutex::InterprocessMutex()' from file '~/Library/Developer/Xcode/DerivedData/Realm-fgnurdgvwrgrprepohogrgawtdgm/Build/Intermediates/Realm.build/Debug/Realm.build/Objects-normal/x86_64/shared_realm.o' to global weak symbol 'realm::util::InterprocessMutex::initialize_statics()' from file 'core/librealm-dbg.a(client_file_access_cache-macosx.dbg.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```

**Comment by bdash** [comment] 2016-12-06 00:01
Does this reproduce with object store's build system, or only when the object store is built as part of Cocoa?

**Comment by jpsim** [comment] 2016-12-06 00:02
I haven't looked into that yet.

**Comment by tgoyne** [comment] 2016-12-07 17:31
This will be fixed by https://github.com/realm/realm-core/pull/2350 and https://github.com/realm/realm-sync/pull/1021.

**Comment by bdash** [comment] 2016-12-12 18:08
Looks like both the core and sync PRs were merged, and there's nothing to be done in the object store for this.

**Closed by bdash** 2016-12-12 18:08 UTC
Labels: S:P2 Backlog, T:Bug
